### PR TITLE
only parse as number if field type matches

### PR DESCRIPTION
**Pull request by isitgeorge**
Text fields are incorrectly parsed as numerical values if they only contain numbers

### CODE REVIEW

**Comment by cristianoliveira** [comment]
Hey @isitgeorge thanks for the contribution. 

Would be nice to add a test for it. Was it a bug you had or something? If so, could you add this as the use case for the test?

**Comment by isitgeorge** [comment]
Sure thing @cristianoliveira cristianoliveira, I'll put a test together.

I'm using the plugin as part of an mailing address form, where the first field could just be a number or text. I had payload validation as part of the backend service that verified that the particular field was a string, which was the problem.

**Comment by isitgeorge** [comment]
Perhaps a specific use case to me; but I couldn't see a reason for an input field to be parsed as a number unless the field specified 😬

**Comment by jonathansp** [comment]
@isitgeorge it makes sense. However, many sites don't define their input's type as number. My suggestion is to add an option such as `strict_convert_number_type:[true|false]` that defaults to `false`.

**Pull request closed without merging**
